[Variables]
SavedThemeName1=Empty theme slot 1 
SavedThemeAuthor1= 
SavedThemeTime1=
SavedThemeActive1=0

SavedThemeName2=Empty theme slot 2
SavedThemeAuthor2=
SavedThemeTime2=
SavedThemeActive2=0

SavedThemeName3=Empty theme slot 3
SavedThemeAuthor3=
SavedThemeTime3=
SavedThemeActive3=0

SavedThemeName4=Empty theme slot 4
SavedThemeAuthor4=
SavedThemeTime4=
SavedThemeActive4=0

SavedThemeName5=Empty theme slot 5
SavedThemeAuthor5=
SavedThemeTime5=
SavedThemeActive5=0

SavedThemeName6=Empty theme slot 6
SavedThemeAuthor6=
SavedThemeTime6=
SavedThemeActive6=0

SavedThemeName7=Empty theme slot 7
SavedThemeAuthor7=
SavedThemeTime7=
SavedThemeActive7=0

SavedThemeName8=Empty theme slot 8
SavedThemeAuthor8=
SavedThemeTime8=
SavedThemeActive8=0

OverwriteText=Overwrite "[#SavedThemeName[#*CURRENTSECTION*]]"?

LoadText="Load"
DefaultThemeText=Empty theme slot [#*CURRENTSECTION*]
SavedText="Saved "

ThemeSlotNumber=1

AppName=Theme Me
AppVersion=1.0
AppCreators=TheyCallMePapa & Cariboudjan
MaxFontSize=(9*#DroptopSize#)
OnOff=1
hb=4
OnOffText=Hide
InfoOnOffText=Off
NumBoxes=2
RoundTo=1

Skin.Width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
Skin.Height=100

varkey=#SKINSPATH#Droptop Community Apps\Apps\Theme_Me-Mike_Boynton\Variables\Variables.inc

PreviousAutoThemeChange=0

ThemeChangeNum=1
AutoChangeTime1=%j
AutoChangeTime2=%H
AutoChangeTime3=%M

CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#

AutoThemeChangeOFF=1

ThemeType=Droptop Theme
CurrentTheme=Cathode Theme