[Variables]
SavedThemeName1=System Theme 
SavedThemeAuthor1=by Mike Boynton 
SavedThemeTime1=#CRLF#Saved 11/03/22 5:36 AM
SavedThemeActive1=1

SavedThemeName2=My custom theme
SavedThemeAuthor2=by Cari
SavedThemeTime2=#CRLF#Saved 11/04/22 8:45 AM
SavedThemeActive2=1

SavedThemeName3=Catppuccin
SavedThemeAuthor3=by PyBash
SavedThemeTime3=#CRLF#Saved 11/04/22 8:44 AM
SavedThemeActive3=1

SavedThemeName4=Code Theme
SavedThemeAuthor4=by Phan
SavedThemeTime4=#CRLF#Saved 11/04/22 8:44 AM
SavedThemeActive4=1

SavedThemeName5=Dracula
SavedThemeAuthor5=by Bunz
SavedThemeTime5=#CRLF#Saved 11/04/22 8:44 AM
SavedThemeActive5=1

SavedThemeName6=Nord
SavedThemeAuthor6=by Bunz
SavedThemeTime6=#CRLF#Saved 11/04/22 8:43 AM
SavedThemeActive6=1

SavedThemeName7=Tranquil_Purple
SavedThemeAuthor7=by Bunz
SavedThemeTime7=#CRLF#Saved 11/04/22 8:43 AM
SavedThemeActive7=1

SavedThemeName8=Ice Cream
SavedThemeAuthor8=by Phan
SavedThemeTime8=#CRLF#Saved 11/04/22 8:43 AM
SavedThemeActive8=1

OverwriteText=Overwrite "[#SavedThemeName[#*CURRENTSECTION*]]"?

LoadText="  Load"
DefaultThemeText=Empty theme slot [#*CURRENTSECTION*]
SavedText="Saved "

ThemeSlotNumber=1

MyVarKey=#SKINSPATH#Droptop Community Apps\Apps\ThemeMe-Mike_Boynton\Variables\Variables.inc

AppName=Theme Me
AppVersion=1.0
AppCreators=Mike Boynton & Cariboudjan
MaxFontSize=9
OnOff=1
hb=4
OnOffText=Hide
InfoOnOffText=Off
NumBoxes=2
RoundTo=1

Skin.Width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
Skin.Height=100

UserKey=#SKINSPATH#Droptop\@Resources\GlobalVar\UserSettings.inc
;Key2=#SKINSPATH#Droptop Community Apps\Apps\ThemeMe-Mike_Boynton\Variables\Variables.inc

CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#
CurrentTheme=Default Theme

