[Variables]
SavedThemeName1=Nord 
SavedThemeAuthor1=by Bunz#CRLF#
SavedThemeTime1=11/05/22 8:50 AM
SavedThemeActive1=1

SavedThemeName2=Code Theme
SavedThemeAuthor2=by Phan#CRLF#
SavedThemeTime2=11/05/22 8:51 AM
SavedThemeActive2=1

SavedThemeName3=Ice Cream
SavedThemeAuthor3=by Phan#CRLF#
SavedThemeTime3=11/05/22 8:52 AM
SavedThemeActive3=1

SavedThemeName4=Dracula
SavedThemeAuthor4=by Bunz#CRLF#
SavedThemeTime4=11/05/22 8:53 AM
SavedThemeActive4=1

SavedThemeName5=Catppuccin
SavedThemeAuthor5=by PyBash#CRLF#
SavedThemeTime5=11/05/22 8:53 AM
SavedThemeActive5=1

SavedThemeName6=System Theme
SavedThemeAuthor6=by Mike Boynton#CRLF#
SavedThemeTime6=11/05/22 8:53 AM
SavedThemeActive6=1

SavedThemeName7=#ThemeName99#
SavedThemeAuthor7=by Cari#CRLF#
SavedThemeTime7=11/05/22 8:54 AM
SavedThemeActive7=1

SavedThemeName8=Tranquil_Purple
SavedThemeAuthor8=by Bunz#CRLF#
SavedThemeTime8=11/05/22 8:55 AM
SavedThemeActive8=1

OverwriteText=Overwrite "[#SavedThemeName[#*CURRENTSECTION*]]"?

LoadText="  Load"
DefaultThemeText=Empty theme slot [#*CURRENTSECTION*]
SavedText="Saved "

ThemeSlotNumber=1

MyVarKey=#SKINSPATH#Droptop Community Apps\Apps\Theme_Me-Mike_Boynton\Variables\Variables.inc

AppName=Theme Me
AppVersion=1.0
AppCreators=Mike Boynton & Cariboudjan
MaxFontSize=9
OnOff=1
hb=4
OnOffText=Hide
InfoOnOffText=Off
NumBoxes=2
RoundTo=1

Skin.Width=(#DropdownMenuWidth#+2-(#DropdownMenuCutout#*2))
Skin.Height=100

UserKey=#SKINSPATH#Droptop\@Resources\GlobalVar\UserSettings.inc
CurrentItemX=#DropdownMenuWidth#
CurrentItemY=#DropdownItemHeight#
CurrentBoxX=#DropdownMenuWidth#
CurrentFontSize=#DropdownItemFontSize#
CurrentTheme=System Theme by Mike Boynton
ThemeType=Custom Theme
